<?php

namespace App\Filament\Resources\BraceletEvents\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Placeholder;
use Filament\Schemas\Schema;

class BraceletEventForm
{
    public static function configure(Schema $schema): Schema
    {
        // READ-ONLY VIEW - BraceletEvents are auto-generated by the bracelet
        return $schema
            ->components([
                Placeholder::make('bracelet_id')
                    ->label('Bracelet ID'),
                Placeholder::make('event_type')
                    ->label('Type d\'Événement'),
                Placeholder::make('latitude')
                    ->label('Latitude'),
                Placeholder::make('longitude')
                    ->label('Longitude'),
                Placeholder::make('accuracy')
                    ->label('Précision (m)'),
                Placeholder::make('battery_level')
                    ->label('Niveau de Batterie'),
                Placeholder::make('resolved')
                    ->label('Résolu'),
                Placeholder::make('resolved_at')
                    ->label('Date de Résolution'),
                Placeholder::make('created_at')
                    ->label('Date de Création'),
            ]);
    }
}
